In [1]:
import numpy as np
import pandas as pd

input_file = "baseDatosNumerica.csv"
df = pd.read_csv(input_file, header = 0, delimiter = ";")
# put the original column names in a python list
original_headers = list(df.columns.values)

In [2]:
type(df)
df.head()
df = df.dropna()

In [3]:
y = df["Incidente"]
X = df.drop(["Incidente"], axis=1)
X.head()

,Hora,Codigo DANE,Barrio,Dia = Lunes,Dia = Martes,Dia = Miercoles,Dia = Viernes,Dia = Jueves,Dia = Sabado,Dia = Domingo,...,Movil Victima = PASAJERO BARCO,Movil Victima = PASAJERO TAXI,Movil Victima = -,Movil Victima = PASAJERO METRO,Movil Victima = TRIPULANTE AERONAVE,Movil Victima = PASAJERO AERONAVE,Sexo = MASCULINO,Sexo = FEMENINO,Sexo = -,Edad
0,0.0,0.001614,0.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,48.0
1,0.0,0.003788,1.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,39.0
2,0.0,0.004474,2.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,18.0
3,0.0,0.000000,3.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,15.0
4,0.0,0.005086,4.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,58.0

In [4]:
y.head()

0    Amenaza
1    Amenaza
2    Amenaza
3    Amenaza
4    Amenaza
Name: Incidente, dtype: object

In [102]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
#from sklearn.model_selection import cross_validate
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(7,5))
#from sklearn.model_selection import cross_val_score
#scoring = ['precision', 'recall', 'accuracy']
#scores = cross_validate(clf, X_svd, y, cv=5, scoring=scoring, return_train_score=False)
#print(scores)

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [103]:
X_test.head()

,Hora,Codigo DANE,Barrio,Dia = Lunes,Dia = Martes,Dia = Miercoles,Dia = Viernes,Dia = Jueves,Dia = Sabado,Dia = Domingo,...,Movil Victima = PASAJERO BARCO,Movil Victima = PASAJERO TAXI,Movil Victima = -,Movil Victima = PASAJERO METRO,Movil Victima = TRIPULANTE AERONAVE,Movil Victima = PASAJERO AERONAVE,Sexo = MASCULINO,Sexo = FEMENINO,Sexo = -,Edad
63173,0.498583,0.063310,544.0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,26.0
73484,0.513820,0.667655,12171.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,19.0
135840,0.519844,0.669027,2021.0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,35.0
53854,0.490432,0.749166,5917.0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,45.0
169773,0.644578,0.643650,15460.0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,14.0

In [104]:
X_train.head()

,Hora,Codigo DANE,Barrio,Dia = Lunes,Dia = Martes,Dia = Miercoles,Dia = Viernes,Dia = Jueves,Dia = Sabado,Dia = Domingo,...,Movil Victima = PASAJERO BARCO,Movil Victima = PASAJERO TAXI,Movil Victima = -,Movil Victima = PASAJERO METRO,Movil Victima = TRIPULANTE AERONAVE,Movil Victima = PASAJERO AERONAVE,Sexo = MASCULINO,Sexo = FEMENINO,Sexo = -,Edad
117179,0.489369,0.717512,34.0,0,0,0,0,1,0,0,...,0,0,1,0,0,0,1,0,0,50.0
88445,0.784904,0.219020,1433.0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,35.0
148187,0.490432,0.443718,19873.0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,35.0
102485,0.612686,0.643650,17722.0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,35.0
29467,0.034727,0.008631,5509.0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,1,0,0,39.0

In [105]:
clf.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(6, 5), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [106]:
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 3722,     0,  6075,     0,     0,     0],
       [  292,     0,  1738,     0,     0,     0],
       [ 2967,     0, 15810,     0,     0,     0],
       [  939,     0,  5775,     0,     0,     0],
       [  253,     0,  1788,     0,     0,     0],
       [ 1400,     0,  6408,     0,     0,     0]], dtype=int64)

In [107]:
recall_score(y_test, y_pred, average=None)

array([0.37991222, 0.        , 0.84198754, 0.        , 0.        ,
       0.        ])

In [108]:
precision_score(y_test, y_pred, average=None)

C:\Users\Camilo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

array([0.38880184, 0.        , 0.42054583, 0.        , 0.        ,
       0.        ])

In [109]:
accuracy_score(y_test, y_pred)

0.4141030805436004

In [117]:
from sklearn_porter import Porter

In [118]:
porter = Porter(clf, language='js')
output = porter.export(embed_data=True)
print(output)

var MLPClassifier = function(hidden, output, layers, weights, bias) {

    this.hidden = hidden.toUpperCase();
    this.output = output.toUpperCase();
    this.network = new Array(layers.length + 1);
    for (var i = 0, l = layers.length; i < l; i++) {
        this.network[i + 1] = new Array(layers[i]).fill(0.);
    }
    this.weights = weights;
    this.bias = bias;

    var compute = function(activation, v) {
        switch (activation) {
            case 'LOGISTIC':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = 1. / (1. + Math.exp(-v[i]));
                }
                break;
            case 'RELU':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = Math.max(0, v[i]);
                }
                break;
            case 'TANH':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = Math.tanh(v[i]);
                }
                break;
            case 'SOFTMAX':
                var max = Number.NEGATIVE_INFINITY;
                for (var i = 0, l = v.length; i < l; i++) {
                    if (v[i] > max) {
                        max = v[i];
                    }
                }
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = Math.exp(v[i] - max);
                }
                var sum = 0.0;
                for (var i = 0, l = v.length; i < l; i++) {
                    sum += v[i];
                }
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] /= sum;
                }
                break;
        }
        return v;
    };

    this.predict = function(neurons) {
        this.network[0] = neurons;

        for (var i = 0; i < this.network.length - 1; i++) {
            for (var j = 0; j < this.network[i + 1].length; j++) {
                this.network[i + 1][j] = this.bias[i][j];
                for (var l = 0; l < this.network[i].length; l++) {
                    this.network[i + 1][j] += this.network[i][l] * this.weights[i][l][j];
                }
            }
            if ((i + 1) < (this.network.length - 1)) {
                this.network[i + 1] = compute(this.hidden, this.network[i + 1]);
            }
        }
        this.network[this.network.length - 1] = compute(this.output, this.network[this.network.length - 1]);

        if (this.network[this.network.length - 1].length == 1) {
            if (this.network[this.network.length - 1][0] > .5) {
                return 1;
            }
            return 0;
        } else {
            var classIdx = 0;
            for (var i = 0, l = this.network[this.network.length - 1].length; i < l; i++) {
                classIdx = this.network[this.network.length - 1][i] > this.network[this.network.length - 1][classIdx] ? i : classIdx;
            }
            return classIdx;
        }

    };

};

if (typeof process !== 'undefined' && typeof process.argv !== 'undefined') {
    if (process.argv.length - 2 === 70) {

        // Features:
        var features = process.argv.slice(2);

        // Parameters:
        const layers = [3, 4, 6];
        const weights = [[[-0.07687577149115812, 0.796146110447301, -7.352954819866199], [-0.03607698374743478, 0.33782888074176604, -3.5884525299942993], [-0.20064956935388834, -0.5022625413816036, -4.381839656988684], [0.181116671682232, 0.53891271364261, -2.712484932364259], [-0.21551877224259933, 0.15518119126204352, -1.6186321996784165], [0.3226977475512713, 0.04295284584907162, -2.2991491415206786], [-0.263678579396855, 0.06780699444439357, -1.9865921434977416], [0.057295966309594375, 0.37783234419552264, -1.2959196320458857], [-0.20748662624036146, -0.4918611061955175, 0.19962510172776113], [0.04397045037674421, -1.9380588223690822, -0.27862318452087637], [0.22048614670640235, 0.03697600850381509, -1.187638119318053], [0.2520008877756272, -0.33675836311511526, -0.458248553927088], [-0.24587907997143796, -0.071002443277061, -0.23673698092833273], [-0.13658479344314642, 0.004069210133941775, -0.07094346296890204], [0.04931087541093649, -0.2102077285374751, 0.06425963106089688], [0.2538334016012867, 0.19292828633018086, -0.2603056502587832], [-0.22496460895503254, -0.03057578306961956, -0.15040453316719313], [-0.1834048418773695, -0.2605478339392317, 0.2519556157099366], [0.038549045194638594, -0.15847686825297352, -0.10486794512085057], [0.2693750556566946, -0.26036593976991457, -0.23564627265884658], [0.2277380060223111, 0.13427975611075904, 0.17718157465302883], [-0.036704195585153615, -0.1966695115633064, 0.04806660352008447], [-0.23535995421297254, -0.21193319907898397, 0.01627644949843642], [-0.11588260333806345, 0.19881850365191833, 0.02484142254646909], [-0.14658162621130183, -0.24244086074746568, 0.1817072598286136], [0.08147644056556463, 0.22724432550093562, 0.013292994839244059], [-0.030483348733446314, 0.20538587999039915, -0.23208101256748492], [0.32002500712948057, -0.3543333428867968, -0.4443913737999376], [0.27640927729827763, -0.009044629800667022, -0.20278866092316059], [-0.06956881554921596, 0.023433684455310255, 0.15444422744541364], [0.28140709248929696, -0.2853601825133854, -0.0824830744543036], [-0.236314211234816, 0.027258149039887065, -0.6956393946225502], [-0.01688240554893706, 2.1346389444445855, -10.438447064243585], [-0.016693285388003444, 1.5667745931211452, -4.742600701621081], [0.16277355887487027, 0.43876468963048115, 0.06293962886118157], [0.08570312447607858, -1.5151483221152207, -1.437361655662962], [-0.27273405847446885, 0.4236455435903573, -5.016221907823825], [0.05846162222182829, -0.41463808497927274, -0.23065385350054307], [0.28613739881608125, 0.22506405648266264, -0.16923103029299966], [-0.23259572658627173, 2.524053036461494, -9.202746365353619], [0.07967540489948725, -0.020791470605386695, -0.17722188257706853], [-0.1396394513844209, -0.3109257622999911, 0.15547684023124816], [-0.13094206645362583, 0.13618728680117254, -0.41842998130518977], [-0.1461833348493792, 0.018849399919884584, -0.2551189067817148], [-0.2694914129868415, 0.25000101129640895, 0.06176000974842695], [-0.0938364000313256, -0.21371688556140395, -0.28125887861630144], [0.024880311841426406, -0.21944808183190664, -0.2020860860159048], [-0.19234156674821296, 0.12228460549718663, -0.15945115128488382], [-0.12720474935758258, 0.3507734030519268, -1.4332016995764219], [-0.2647993058254548, 0.11067325749327689, 0.11370244067655784], [0.5050415848455206, -0.7018018099486709, -7.291327547255232], [-0.16219021128257166, 1.3691219803694035, -4.541052092662945], [0.26906370698203264, 0.3766470567734795, -1.1428021303361788], [-0.046064980786130125, 0.05655823490604938, -2.141323083227727], [-0.03999332089462349, -0.2283489678521943, -0.2773228260937218], [0.07078907046942501, 0.009512908430783293, -1.089108552009292], [0.026180738951413877, -0.09843682045554365, -0.41366419411368166], [-0.24455315672859723, -0.028922095994457442, -0.8317557012227568], [0.2712730688695203, -0.0869199788566591, -0.797611362851496], [-0.27629110749568897, 0.2690508328117893, -0.18087862379536412], [0.0854213758082317, -0.2649592732862519, -0.37981101456760014], [0.0390764087017781, -0.1437975074443845, 0.0014942142303540095], [0.015406883301994662, 0.05965081838837415, -0.09991555994145188], [0.0319973115632904, 0.013678146331655507, -0.03793236246488984], [0.21850309558607417, 0.03516600821819191, -0.07060076256780011], [0.14594741319942614, 0.7628085552630911, -9.212762228607794], [0.14791795450020295, 0.5130656641268749, -8.760164429312475], [0.11078756807441449, -0.2351765771520585, 0.05460183478575168], [-1.6397927700539265, -0.10852215379633846, -34.94378949150086], [1.2866288592948594, 14.004018655822973, -91.77006879075452]], [[0.1563214551296518, -0.6751781642430003, -0.777066061817774, 0.0152841041913465], [9.98872409843116, -1.0998702973580714, -0.10889458299655502, -8.017750545614156], [9.311235612774324, -0.30442631930819347, 0.10054278045135012, -8.676232402388916]], [[-0.1999198458950299, -0.03254406074821269, -0.0341218897317157, 0.010904195502750232, -0.02313201783669803, 0.034893167741018284], [-0.7113211560436222, -0.10678816058036371, 0.5314734951647045, 0.7682656559872834, 0.6173891212041539, 0.6515278625669757], [0.016971518450540204, 0.07499476972955366, -0.4994514476081977, -0.5940046612337367, 0.09509052527250071, 0.10268392126542304], [10.032840606931295, -0.9946454948232291, 2.0815319697230956, -4.254894720251847, 2.820110678947846, -10.691252552156605]]];
        const bias = [[0.0810561537061654, 1.0023047814778034, -18.330050416467355], [-21.23503888002213, -0.7435643997428217, -0.44098089012681085, 14.796409852659677], [15.375833602521736, 4.896030110388993, 8.40646860827136, -9.109719599653474, 3.917707506655101, -23.10378655257917]];

        // Prediction:
        var clf = new MLPClassifier('relu', 'softmax', layers, weights, bias);
        var prediction = clf.predict(features);
        console.log(prediction);

    }
}